HOUSE PRICE PREDICTION   

Given these home prices find out price of a home that has 3000sqftarea,3 bedrooms,40 year old
2500sqftarea,4 bedrooms,5 year old

In [5]:
import pandas as pd
import numpy as np
from sklearn import linear_model


In [6]:
df=pd.read_csv('/content/houseprimultiple.csv')
df

Area  Bedrooms  Age  Price
0      2600       3.0   20  55000
1      3000       4.0   15  56500
2      3200       NaN   18  61000
3      3600       3.0   20  59000
4      4000       5.0    8  76000

In [7]:
#for handling missing value we'll use median
import math
medianbedroom=math.floor(df.Bedrooms.median())#for integer value
medianbedroom

3

In [8]:
#using fillna function from pandas to fill null value
df.Bedrooms=df.Bedrooms.fillna(medianbedroom)
df

Area  Bedrooms  Age  Price
0      2600       3.0   20  55000
1      3000       4.0   15  56500
2      3200       3.0   18  61000
3      3600       3.0   20  59000
4      4000       5.0    8  76000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0       Area  5 non-null      int64  
 1   Bedrooms  5 non-null      float64
 2   Age       5 non-null      int64  
 3   Price     5 non-null      int64  
dtypes: float64(1), int64(3)
memory usage: 288.0 bytes


In [12]:
reg=linear_model.LinearRegression()
reg.fit(df[['    Area','Bedrooms','Age']],df.Price)

LinearRegression()

In [13]:
reg.coef_

array([ 6.400e+00, -1.066e+04, -2.880e+03])

In [14]:
reg.intercept_

125539.99999999756

In [15]:
reg.predict([[3000,3,15]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([69560.])

In [16]:
 (6.400e+00)*3000+(-1.066e+04)*3+(-2.880e+03)*15+125539.99999999756

69559.99999999756

In [17]:
reg.predict([[26500,4,5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([238100.00000002])